services:
  cookbook:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    volumes:
      - ./services/web/:/usr/src/cookbook/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - app-tier
    
  redis:
    build:
      context: ./services/redis/
    expose:
      - 6379
    networks:
      - app-tier
  
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    networks:
      - app-tier
    depends_on:
      - cookbook

networks:
  app-tier:
    driver: bridge