services:
  flask:
    build: 
      context: .
    command: python3 -m flask --app app:app run --debug --host=0.0.0.0 --port=8000
    volumes:
      - ./services/web/:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - app-tier
    
  redis:
    build:
      context: ./services/redis/
    ports:
      - 6379:6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge